### ISSUE TITLE
Connect to external SMTP server?

### ISSUE THREAD

**Issue by innoreq** [teamatldocker/jira#138]
I can't send emails from Jira - it tells this:

```
An error has occurred with sending the test email:
com.atlassian.mail.MailException: javax.mail.MessagingException: Exception reading response;
  nested exception is:
	java.net.SocketTimeoutException: Read timed out
	at com.atlassian.mail.server.impl.SMTPMailServerImpl.sendWithMessageId(SMTPMailServerImpl.java:222)
	at com.atlassian.mail.server.impl.SMTPMailServerImpl.send(SMTPMailServerImpl.java:159)
	at com.atlassian.jira.plugins.mail.webwork.SendTestMail.doExecute(SendTestMail.java:95)
	at webwork.action.ActionSupport.execute(ActionSupport.java:165)
	at com.atlassian.jira.action.JiraActionSupport.execute(JiraActionSupport.java:63)
	at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:39)
	at webwork.interceptor.NestedInterceptorChain.proceed(NestedInterceptorChain.java:31)
	at webwork.interceptor.ChainedInterceptor.intercept(ChainedInterceptor.java:16)
	at webwork.interceptor.DefaultInterceptorChain.proceed(DefaultInterceptorChain.java:35)
	at webwork.dispatcher.GenericDispatcher.executeAction(GenericDispatcher.java:225)
	at webwork.dispatcher.GenericDispatcher.executeAction(GenericDispatcher.java:154)
	at com.atlassian.jira.web.dispatcher.JiraWebworkActionDispatcher.service(JiraWebworkActionDispatcher.java:138)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
...
```

How can I achieve that Jira sends emails from within the Docker container via an external SMTP server (in this case: smtp.ionos.de)?

**Comment by Firefishy** [comment]
Is likely something to do with your docker networking setup not allowing the connection.

Can you telnet/netcat or similar to the SMTP server from other containers running in the same setup?

**Comment by jhult** [comment]
It is working for me. So, I'm lead to believe it is something like @Firefishy mentioned.

**Comment by jhult** [comment]
@innoreq, is this still an issue for you? If not, I will close this.
